### ISSUE TITLE
É possível rodar o IOTA em servidor web compartilhado? 

### ISSUE THREAD

**Issue by kambene** [eokoe/Iota#3]
Olá,

Sou coloborador do Instituto Ilhabela Sustentavel e usamos o IOTA hospedado na plataforma de Cidades Sustentáveis. Gostaria de saber se é possível instalar o IOTA em servidor web compartilhado que tenha PostgreSQL e Perl? Quais seriam os precedimentos?
Obrigado

**Comment by renatocron** [comment]
É possivel, desde que a pessoa tinha acesso ao shell da maquina e as
dependências instaladas.

https://github.com/eokoe/Iota/wiki/Iota---Como-instalar-uma-c%C3%B3pia-no-linux
https://github.com/eokoe/Iota/wiki/How-to-install-Iota-on-debians-like



<http://www.eokoe.com>Renato Santos
renato.santos@eokoe.com <+henry@eokoe.com>
(11) 3386-8181
www.eokoe.com

2015-03-05 13:35 GMT-03:00 kambene <notifications@github.com>:
