### ISSUE TITLE
List of packages dependancies

### ISSUE THREAD

**Issue by Ziul** [eokoe/Iota#4]
Recently setting up the iota on a vagrant vm, i track the following dependecies while running the `perl script/iota_server.pl -dr` command to check de server. Thought would be nice to share this list thinking on the [wiki](https://github.com/eokoe/Iota/wiki/Iota---Como-instalar-uma-c%C3%B3pia-no-linux) update.

	Archive::Zip
	Catalyst::Authentication::Store::DBIx::Class
	Catalyst::Controller::REST
	Catalyst::Plugin::Authorization::Roles
	Catalyst::Plugin::Params::Nested
	Catalyst::Plugin::Session::DynamicExpiry
	Catalyst::Plugin::Session::PerUser
	Catalyst::Plugin::Session::State::Cookie
	Catalyst::Plugin::Session::Store::File
	Catalyst::Plugin::StatusMessage
	Catalyst::ScriptRunner
	Catalyst::TraitFor::Controller::DBIC::DoesPaging
	Catalyst::View::TT
	Color::Scheme
	Data::Diver
	Data::Manager
	Data::Printer
	DateTime::Format::Duration
	DateTime::Format::Excel
	DateTime::Format::Pg
	DBIx::Class::PassphraseColumn
	DBIx::Class::TimeStamp
	Graphics::Color::RGB
	I18N::AcceptLanguage
	Math::Expression::Evaluator
	MooseX::Traits
	MooseX::Types::Email
	Spreadsheet::ParseExcel::Stream
	Spreadsheet::WriteExcel
	Spreadsheet::XLSX::Fmt2007
	Statistics::Basic
	Statistics::Descriptive
	String::Random
	Template::AutoFilter
	Text2URI
	Text::CSV_XS

**Comment by renatocron** [comment]
Olá,

Tem mais deps do que isso.

Vou conferir porque o Travis parou de funcionar, e ai atualizo o Makefile.PL de acordo.

--

**Comment by Ziul** [comment]
Pelo que mapeamos, achamos essas dependências. São 54 módulos Perl ate o momento.

    ['App::Sqitch',
    'Archive::Zip',
    'Catalyst::Authentication::Store::DBIx::Class',
    'Catalyst::Controller::REST',
    'Catalyst::Devel',
    '-n Catalyst::Plugin::Assets',
    'Catalyst::Plugin::Authorization::Roles',
    'Catalyst::Plugin::Params::Nested',
    'Catalyst::Plugin::Session::DynamicExpiry',
    'Catalyst::Plugin::Session::PerUser',
    'Catalyst::Plugin::Session::State::Cookie',
    'Catalyst::Plugin::Session::Store::File',
    'Catalyst::Plugin::StatusMessage',
    'Catalyst::ScriptRunner',
    'Catalyst::TraitFor::Controller::DBIC::DoesPaging',
    'Catalyst::View::TT',
    'Color::Scheme',
    'Data::Diver',
    'Data::Manager',
    'Data::Printer',
    'DateTime::Format::Duration',
    'DateTime::Format::Excel',
    'DateTime::Format::Pg',
    'DBD::Pg',
    'DBIx::Class',
    'DBIx::Class::PassphraseColumn',
    'DBIx::Class::TimeStamp',
    'Graphics::Color::RGB',
    'I18N::AcceptLanguage',
    'JSON::Any',
    'Math::Expression::Evaluator',
    'Module::Install',
    'MooseX::Traits',
    'MooseX::Types::Email',
    'MooseX::Types::JSON',
    'Spreadsheet::ParseExcel::Stream',
    'Spreadsheet::WriteExcel',
    'Spreadsheet::XLSX::Fmt2007',
    'Statistics::Basic',
    'Statistics::Descriptive',
    'String::Random',
    'Template::AutoFilter',
    'Text2URI',
    'Text::CSV',
    'Text::CSV_XS',
    'Catalyst::ScriptRunner',
    'XML::LibXML', 
    'HTML::HTML5::Writer', 
    'DBD::Pg', 
    'Email::Sender::Transport::SMTP::TLS', 
    'RDF::Endpoint',
    'FCGI',
    'FCGI::ProcManager',
    'XML::Simple']

**Comment by renatocron** [comment]
O makefile deveria conter todas. A lista gerada pela execução só pega as
partes que o código rodou. Quando tem algum require ela não pega, se não
rodar.
O Travis parou de funcionar direito e o pessoal não me respondeu.. Mas até
onde lembro, o makefile estava ok
