### ISSUE TITLE
Type of arg 1 to Data::Printer::p must be one of [@$%&] (not reference constructor)

### ISSUE THREAD

**Issue by Ziul** [eokoe/Iota#5]
Got two errors while starting up the server. Both about **Type of arg 1 to Data::Printer::p must be one of \[@$%&\] (not reference constructor)** into files *lib/Iota/Controller/API/Network.pm:203* and *lib/Iota/Schema/ResultSet/Source.pm:48*. Follows the diff with solution adopted:

    diff --git a/lib/Iota/Controller/API/Network.pm b/lib/Iota/Controller/API/Network.pm
    index 5312342..c725f64 100644
    --- a/lib/Iota/Controller/API/Network.pm
    +++ b/lib/Iota/Controller/API/Network.pm
    @@ -200,7 +200,7 @@ sub list_GET {
         my @objs;
         use DDP;
         p $c->req->params->{user_id};
    -    p \@list;
    +    p @list;
         foreach my $obj (@list) {
             push @objs, {
                 (
    diff --git a/lib/Iota/Schema/ResultSet/Source.pm b/lib/Iota/Schema/ResultSet/Source.pm
    index 13408bb..7950fad 100644
    --- a/lib/Iota/Schema/ResultSet/Source.pm
    +++ b/lib/Iota/Schema/ResultSet/Source.pm
    @@ -45,7 +45,7 @@ sub action_specs {
                   for keys %values;
                 return unless keys %values;
                 use DDP;
    -            p \%values;
    +            p %values;
                 my $old = $self->search(
                     {
                         user_id => $values{user_id},

We just removed the \\ characters from the two files.

**Comment by renatocron** [comment]
Sorry, that should not be committed at first place!

But it's a dev configuration that you can use to allow references
