### ISSUE TITLE
Frontend e configuração

### ISSUE THREAD

**Issue by aldarionsevero** [eokoe/Iota#6]
Já conseguimos configurar as dependências, configurar o banco, e levantar o servidor local para ver a pagina inicial do iota só que com a mensagem de "Página não encontrada!".
![screen_2015-09-10_15-06-48](https://cloud.githubusercontent.com/assets/2432275/9796622/93c96180-57cd-11e5-8cb2-df972e295c49.png)

Estamos agora com dificuldade de levantar a parte frontend juntamente com o servidor web. No arquivo up.sh que vocês sugerem que façamos, mudamos o local e nome do cgi.pl, no de vocês está iota_fastcgi.pl , mas no diretório da aplicação só achamos um arquivo com nome iota_cgi.pl. 

Agora o que não temos idéia de onde colocar é o private_path "/home/iota-app/upload" que o tutorial pede para colocarmos no iota.conf.

**Comment by renatocron** [comment]
Não precisa mudar o nome do cgi não, só do arquivo de conf pra _local.conf

O private path é um diretórios de upload de arquivos.

O problema do not found, é porque precisa configurar uma rede. Tabela
network tem um campo de domínio.

Isso é uma das coisas importantes do Iota. Geralmente o controle de
permissão dos usuários e dos indicadores são por redes.

**Comment by JDias** [comment]
Ola,
tive algumas issues:
no tutorial de instalação:

1- eu troquei o "git clone git://github.com/AwareTI/Iota.git" pelo iotaorg/Iota-RNSP pois o AwareTI não existe mais, apesar de ter este redirecionamento

2 - o DELETE FROM "user" where network_id > 1;  eu troquei pelo institute_id (pois não tinha network id no banco) após eu ter deletado from "network_user" os network_id

3 - após a instalação do frontend consegui http://iota.sisdipe.com.br/ (mas aparentemente nada do que esta ali vem do git clone git://github.com/AwareTI/Iota-Admin-Frontend.git
