### ISSUE TITLE
502 Bad Gateway frequente durante execução da aplicação

### ISSUE THREAD

**Issue by gabrielssilva** [eokoe/Iota#7]
Conseguimos subir uma instância local do Iota com o frontend de administração. Por enquanto, tudo funciona bem com exceção de um erro frequente, que derruba a aplicação e retorna 502 Bad Gateway.

Não encontramos lógica aparente para a ocorrência do problema, aparentemente é aleatório. Também consultamos alguns arquivos de log (logs do nginx, e /tmp/iota-prod...), mas não encontramos nada expressivo para a identificar o problema. 

Segue a saída do arquivo de log que possui o maior número de mensagens (/var/log/nginx/error.log), equivalente ao momento em que o problema ocorre.

```
|   -> /stash_tela" while reading upstream, client: 10.10.10.1, server: latino.org, request: "GET /br/SP/sao-paulo/indicador-de-teste HTTP/1.1", upstream: "fastcgi://127.0.0.1:8000", host: "latino.org", referrer: "http://latino.org/indicador-de-teste?view=table"
2015/09/15 18:17:49 [error] 6995#0: *1175 FastCGI sent in stderr: "_cidade                                    | 0.026165s |
|  -> /build_indicators_menu                                 | 0.015624s |
| /network_indicator_render                                  | 0.003208s |
| /end                                                       | 0.046218s |
|  -> Iota::View::HTML->process                              | 0.045637s |
'------------------------------------------------------------+-----------'" while reading upstream, client: 10.10.10.1, server: latino.org, request: "GET /br/SP/sao-paulo/indicador-de-teste HTTP/1.1", upstream: "fastcgi://127.0.0.1:8000", host: "latino.org", referrer: "http://latino.org/indicador-de-teste?view=table"
2015/09/15 18:17:54 [error] 6995#0: *1173 upstream prematurely closed connection while reading response header from upstream, client: 10.10.10.1, server: latino.org, request: "GET /api/public/network?user_id=4&_=1442341069281 HTTP/1.1", upstream: "fastcgi://127.0.0.1:8000", host: "latino.org", referrer: "http://latino.org/br/SP/sao-paulo/indicador-de-teste"
2015/09/15 18:17:54 [error] 6995#0: *1175 upstream prematurely closed connection while reading response header from upstream, client: 10.10.10.1, server: latino.org, request: "GET /me/account HTTP/1.1", upstream: "fastcgi://127.0.0.1:8000", host: "latino.org", referrer: "http://latino.org/br/SP/sao-paulo/indicador-de-teste"
```

**Comment by renatocron** [comment]
Olá Gabriel,

Ainda estou pra te escrever um email com mais detalhes sobre o
funcionamento,

mas, no momento, recomendo você trocar o FastCGI no nginx por um proxy_pass
(vc sabe usar?)
e ai você sobe o iota usando

perl script/iota_server.pl -drp 5050

por exemplo, e ai no nginx vc faz um

proxy_pass http://localhost:5050


Assim,
-d serve pra ligar o debug
-r pra reiniciar assim que vc mudar algum codigo
-p a porta para subir.








Renato Santos
renato.santos@eokoe.com
(11) 3386-8181
www.eokoe.com
b-cam.com.br

2015-09-16 15:39 GMT-03:00 Gabriel Silva <notifications@github.com>:

**Comment by gabrielssilva** [comment]
Olá Renato, muito obrigado. Um feedback:

substituímos o FastCGI pelo proxy_pass.
A aplicação não voltou a cair, aparentemente resolveu o problema.
